### ISSUE TITLE
No servers configured for repository

### ISSUE THREAD

**Issue by eyqs** [mediocregopher/chroagh#1]
After extracting the `mediocregopher-chroagh-bb0c97a` tarball, I ran:
```sudo sh -e installer/main.sh -r arch -t core -m 'http://mirror.csclub.uwaterloo.ca/archlinux/$repo/os/$arch'```

I ended up with this error after downloading and extracting base packages, creating groups, and updating the trust database:
```
resolving dependencies...
looking for conflicting packages...

Packages (93) [trimmed]

Total Installed Size:  401.62 MiB

:: Proceed with installation? [Y/n] 
error: no servers configured for repository: core
error: no servers configured for repository: extra
error: failed to commit transaction (no servers configured for repository)
Errors occurred, no packages were upgraded.
Unmounting /tmp/main.sh.prl/arch-x86_64...
Sending SIGTERM to processes under /tmp/main.sh.prl/arch-x86_64...
```

**Comment by mediocregopher** [comment]
I'm afraid I'm not able to reproduce, creating a new chroot with a manually specified mirror works fine for me. But I'm on an arm so possibly it could have something to do with that. Could you copy/paste this into your shell inside chroagh and rerun?

```bash
(cat << 'EOF'
diff --git a/installer/arch/bootstrap b/installer/arch/bootstrap
index e5be03e..12b0711 100644
--- a/installer/arch/bootstrap
+++ b/installer/arch/bootstrap
@@ -200,6 +200,12 @@ sh -e $BINDIR/enter-chroot -x -c "$(dirname $BOOTSTRAPCHROOT)" find $FETCHDIRDBcman-key --populate archlinuxarm

         fi

+        echo '#### catting pacman.conf ####'
+        cat /etc/pacman.conf
+        echo '#### catting pacman mirrorlist ####'
+        cat /etc/pacman.d/mirrorlist
+        echo '#### Calling pacman ####'
+
         # Force overwritting packages files in the bootstrap, without any sort
         # of dependency checking: this makes sure package content are properly
         # recorded
EOF
) | patch -p1
```

and if you could post the entire output from the command (I know it's a lot) that'd be really helpful, especially to see those debug lines the patch adds.

**Comment by eyqs** [comment]
Both pacman.conf and the mirrorlist are the same as the defaults. In particular, all the mirrors in the list are commented out. Did your mirrorlist start with some uncommented mirrors?

**Comment by eyqs** [comment]
The x86 mirrorlist [has no uncommented mirrors](https://github.com/mediocregopher/chroagh/pull/3#issuecomment-415901711), so the prepare script has a section to append `$MIRROR` [to the mirrorlist](https://github.com/mediocregopher/chroagh/blob/master/installer/arch/prepare#L126). But the bootstrap script also needs a mirror, which is addressed by [this pull request](https://github.com/mediocregopher/chroagh/pull/4). Nevertheless, we might want to reorganize these scripts in the future.
